CREATE TABLE IF NOT EXISTS `system_settings` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_id` VARCHAR(64) NOT NULL DEFAULT 'default',
  `key` VARCHAR(128) NOT NULL,
  `value` TEXT NOT NULL,
  `value_type` VARCHAR(16) NOT NULL DEFAULT 'string',
  `draft_value` TEXT NOT NULL,
  `draft_value_type` VARCHAR(16) NOT NULL DEFAULT 'string',
  `is_published` TINYINT(1) NOT NULL DEFAULT 1,
  `published_at` DATETIME(3) NULL,
  `published_by` BIGINT NOT NULL DEFAULT 0,
  `publish_note` VARCHAR(255) NOT NULL DEFAULT '',
  `group_name` VARCHAR(64) NOT NULL DEFAULT '',
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_system_settings_tenant_key` (`tenant_id`, `key`),
  KEY `idx_system_settings_tenant` (`tenant_id`),
  KEY `idx_system_settings_group_name` (`group_name`),
  KEY `idx_system_settings_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
