CREATE TABLE IF NOT EXISTS `scheduled_tasks` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_id` VARCHAR(64) NOT NULL DEFAULT 'default',
  `name` VARCHAR(128) NOT NULL,
  `spec` VARCHAR(64) NOT NULL,
  `command` VARCHAR(1024) NOT NULL,
  `timeout_sec` INT NOT NULL DEFAULT 0,
  `concurrency_policy` VARCHAR(16) NOT NULL DEFAULT 'forbid',
  `enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `last_run_at` DATETIME(3) NULL,
  `last_status` VARCHAR(32) NULL,
  `last_message` VARCHAR(255) NULL,
  `created_at` DATETIME(3) NULL,
  `updated_at` DATETIME(3) NULL,
  `deleted_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_scheduled_tasks_tenant_name` (`tenant_id`, `name`),
  KEY `idx_scheduled_tasks_tenant` (`tenant_id`),
  KEY `idx_scheduled_tasks_enabled` (`enabled`),
  KEY `idx_scheduled_tasks_enabled_id` (`enabled`, `id`),
  KEY `idx_scheduled_tasks_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
