package port

import (
	"context"

	"gin-scaffold/internal/model"
)

// AnnouncementService generated by cmd/gen crud.
type AnnouncementService interface {
	Create(ctx context.Context, in *model.Announcement) error
	Update(ctx context.Context, in *model.Announcement) error
	GetByID(ctx context.Context, id int64) (*model.Announcement, error)
	List(ctx context.Context, page, pageSize int) ([]model.Announcement, int64, error)
	Delete(ctx context.Context, id int64) error
}
