package routes

import (
	"github.com/gin-gonic/gin"

	adminhandler "gin-scaffold/api/handler/admin"
	"gin-scaffold/middleware"
)

// registerAdminAnnouncementRoutes generated by cmd/gen crud.
func registerAdminAnnouncementRoutes(admin *gin.RouterGroup, h *adminhandler.AnnouncementHandler) {
	admin.GET("/announcements", middleware.RequirePermission("announcement:read"), h.List)
	admin.GET("/announcements/:id", middleware.RequirePermission("announcement:read"), h.Get)
	admin.POST("/announcements", middleware.RequirePermission("announcement:write"), h.Create)
	admin.PUT("/announcements/:id", middleware.RequirePermission("announcement:write"), h.Update)
	admin.DELETE("/announcements/:id", middleware.RequirePermission("announcement:write"), h.Delete)
}
