package model

import (
	"time"

	"gorm.io/gorm"
)

// Announcement generated by cmd/gen crud.
type Announcement struct {
	ID        int64          `gorm:"primaryKey;autoIncrement" json:"id"`
	Title string `gorm:"not null" json:"title"`
	Content string `gorm:"not null" json:"content"`
	Status string `gorm:"not null" json:"status"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`
}

func (Announcement) TableName() string {
	return "announcements"
}
