package adminhandler

import (
	"net/http"

	"github.com/gin-gonic/gin"

	adminreq "gin-scaffold/api/request/admin"
	"gin-scaffold/api/response"
	"gin-scaffold/internal/model"
	"gin-scaffold/internal/pkg/errcode"
	"gin-scaffold/internal/service/port"
)

// AnnouncementHandler generated by cmd/gen crud.
type AnnouncementHandler struct {
	svc port.AnnouncementService
}

func NewAnnouncementHandler(s port.AnnouncementService) *AnnouncementHandler {
	return &AnnouncementHandler{svc: s}
}

func (h *AnnouncementHandler) List(c *gin.Context) {
	var q adminreq.PageQuery
	_ = c.ShouldBindQuery(&q)
	rows, total, err := h.svc.List(c.Request.Context(), q.Page, q.PageSize)
	if err != nil {
		response.FailHTTP(c, http.StatusInternalServerError, errcode.InternalError, errcode.KeyInternal, err.Error())
		return
	}
	response.OK(c, gin.H{"total": total, "list": rows})
}

func (h *AnnouncementHandler) Get(c *gin.Context) {
	var uri adminreq.AnnouncementIDURI
	if err := c.ShouldBindUri(&uri); err != nil {
		response.FailHTTP(c, http.StatusBadRequest, errcode.BadRequest, errcode.KeyInvalidParam, err.Error())
		return
	}
	row, err := h.svc.GetByID(c.Request.Context(), uri.ID)
	if err != nil {
		response.FailHTTP(c, http.StatusNotFound, errcode.NotFound, errcode.KeyInvalidParam, err.Error())
		return
	}
	response.OK(c, row)
}

func (h *AnnouncementHandler) Create(c *gin.Context) {
	var req adminreq.AnnouncementCreateRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		response.FailHTTP(c, http.StatusBadRequest, errcode.BadRequest, errcode.KeyInvalidParam, err.Error())
		return
	}
	in := &model.Announcement{
		Title: req.Title,
		Content: req.Content,
		Status: req.Status,
	}
	if err := h.svc.Create(c.Request.Context(), in); err != nil {
		response.FailHTTP(c, http.StatusInternalServerError, errcode.InternalError, errcode.KeyInternal, err.Error())
		return
	}
	response.OK(c, in)
}

func (h *AnnouncementHandler) Update(c *gin.Context) {
	var uri adminreq.AnnouncementIDURI
	if err := c.ShouldBindUri(&uri); err != nil {
		response.FailHTTP(c, http.StatusBadRequest, errcode.BadRequest, errcode.KeyInvalidParam, err.Error())
		return
	}
	var req adminreq.AnnouncementUpdateRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		response.FailHTTP(c, http.StatusBadRequest, errcode.BadRequest, errcode.KeyInvalidParam, err.Error())
		return
	}
	in := &model.Announcement{ID: uri.ID}
	if req.Title != nil {
		in.Title = *req.Title
	}
	if req.Content != nil {
		in.Content = *req.Content
	}
	if req.Status != nil {
		in.Status = *req.Status
	}
	if err := h.svc.Update(c.Request.Context(), in); err != nil {
		response.FailHTTP(c, http.StatusInternalServerError, errcode.InternalError, errcode.KeyInternal, err.Error())
		return
	}
	response.OK(c, in)
}

func (h *AnnouncementHandler) Delete(c *gin.Context) {
	var uri adminreq.AnnouncementIDURI
	if err := c.ShouldBindUri(&uri); err != nil {
		response.FailHTTP(c, http.StatusBadRequest, errcode.BadRequest, errcode.KeyInvalidParam, err.Error())
		return
	}
	if err := h.svc.Delete(c.Request.Context(), uri.ID); err != nil {
		response.FailHTTP(c, http.StatusInternalServerError, errcode.InternalError, errcode.KeyInternal, err.Error())
		return
	}
	response.OK(c, gin.H{"deleted": true})
}
