package adminreq

// AnnouncementCreateRequest generated by cmd/gen crud.
type AnnouncementCreateRequest struct {
	Title string `json:"title" binding:"required,max=128"`
	Content string `json:"content" binding:"required"`
	Status string `json:"status" binding:"oneof=draft"`
}

// AnnouncementUpdateRequest generated by cmd/gen crud.
type AnnouncementUpdateRequest struct {
	Title *string `json:"title" binding:"omitempty,required,max=128"`
	Content *string `json:"content" binding:"omitempty,required"`
	Status *string `json:"status" binding:"omitempty,oneof=draft"`
}

// AnnouncementIDURI generated by cmd/gen crud.
type AnnouncementIDURI struct {
	ID int64 `uri:"id" binding:"required,min=1"`
}
