CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
  request_id VARCHAR(64) NULL,
  user_id BIGINT NOT NULL DEFAULT 0,
  role VARCHAR(32) NULL,
  actor_type VARCHAR(16) NOT NULL DEFAULT 'anonymous',
  action VARCHAR(16) NOT NULL,
  path VARCHAR(512) NOT NULL,
  query VARCHAR(1024) NULL,
  status INT NOT NULL,
  latency_ms INT NOT NULL DEFAULT 0,
  client_ip VARCHAR(64) NULL,
  created_at TIMESTAMP(3) NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_request ON audit_logs (request_id);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs (created_at);
CREATE INDEX IF NOT EXISTS idx_audit_user_created ON audit_logs (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_audit_tenant_created ON audit_logs (tenant_id, created_at);
