CREATE TABLE IF NOT EXISTS user_roles (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
  user_id BIGINT NOT NULL,
  role VARCHAR(64) NOT NULL,
  created_at TIMESTAMP(3) NULL,
  updated_at TIMESTAMP(3) NULL,
  deleted_at TIMESTAMP(3) NULL,
  CONSTRAINT uk_user_tenant_role UNIQUE (tenant_id, user_id, role)
);

CREATE INDEX IF NOT EXISTS idx_user_roles_tenant ON user_roles (tenant_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_deleted_at ON user_roles (deleted_at);
