CREATE TABLE IF NOT EXISTS roles (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
  code VARCHAR(64) NOT NULL,
  name VARCHAR(128) NOT NULL,
  created_at TIMESTAMP(3) NULL,
  updated_at TIMESTAMP(3) NULL,
  deleted_at TIMESTAMP(3) NULL,
  CONSTRAINT uk_roles_tenant_code UNIQUE (tenant_id, code)
);

CREATE INDEX IF NOT EXISTS idx_roles_tenant ON roles (tenant_id);
CREATE INDEX IF NOT EXISTS idx_roles_deleted_at ON roles (deleted_at);

CREATE TABLE IF NOT EXISTS user_roles (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
  user_id BIGINT NOT NULL,
  role VARCHAR(64) NOT NULL,
  created_at TIMESTAMP(3) NULL,
  updated_at TIMESTAMP(3) NULL,
  deleted_at TIMESTAMP(3) NULL,
  CONSTRAINT uk_user_tenant_role UNIQUE (tenant_id, user_id, role)
);

CREATE INDEX IF NOT EXISTS idx_user_roles_tenant ON user_roles (tenant_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_deleted_at ON user_roles (deleted_at);

CREATE TABLE IF NOT EXISTS role_permissions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
  role VARCHAR(64) NOT NULL,
  permission VARCHAR(128) NOT NULL,
  created_at TIMESTAMP(3) NULL,
  updated_at TIMESTAMP(3) NULL,
  deleted_at TIMESTAMP(3) NULL,
  CONSTRAINT uk_role_tenant_permission UNIQUE (tenant_id, role, permission)
);

CREATE INDEX IF NOT EXISTS idx_role_permissions_tenant ON role_permissions (tenant_id);
CREATE INDEX IF NOT EXISTS idx_role_permissions_deleted_at ON role_permissions (deleted_at);
