CREATE TABLE IF NOT EXISTS system_settings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
  "key" VARCHAR(128) NOT NULL,
  value TEXT NOT NULL,
  value_type VARCHAR(16) NOT NULL DEFAULT 'string',
  draft_value TEXT NOT NULL,
  draft_value_type VARCHAR(16) NOT NULL DEFAULT 'string',
  is_published BOOLEAN NOT NULL DEFAULT TRUE,
  published_at TIMESTAMP(3) NULL,
  published_by BIGINT NOT NULL DEFAULT 0,
  publish_note VARCHAR(255) NOT NULL DEFAULT '',
  group_name VARCHAR(64) NOT NULL DEFAULT '',
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP(3) NULL,
  CONSTRAINT uk_system_settings_tenant_key UNIQUE (tenant_id, "key")
);

CREATE INDEX IF NOT EXISTS idx_system_settings_tenant ON system_settings (tenant_id);
CREATE INDEX IF NOT EXISTS idx_system_settings_group_name ON system_settings (group_name);
CREATE INDEX IF NOT EXISTS idx_system_settings_deleted_at ON system_settings (deleted_at);
