CREATE TABLE IF NOT EXISTS scheduled_tasks (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
  name VARCHAR(128) NOT NULL,
  spec VARCHAR(64) NOT NULL,
  command VARCHAR(1024) NOT NULL,
  timeout_sec INT NOT NULL DEFAULT 0,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  last_run_at TIMESTAMP(3) NULL,
  last_status VARCHAR(32) NULL,
  last_message VARCHAR(255) NULL,
  created_at TIMESTAMP(3) NULL,
  updated_at TIMESTAMP(3) NULL,
  deleted_at TIMESTAMP(3) NULL,
  CONSTRAINT uk_scheduled_tasks_tenant_name UNIQUE (tenant_id, name)
);

CREATE INDEX IF NOT EXISTS idx_scheduled_tasks_tenant ON scheduled_tasks (tenant_id);
CREATE INDEX IF NOT EXISTS idx_scheduled_tasks_enabled ON scheduled_tasks (enabled);
CREATE INDEX IF NOT EXISTS idx_scheduled_tasks_deleted_at ON scheduled_tasks (deleted_at);

CREATE TABLE IF NOT EXISTS scheduled_task_logs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
  task_id BIGINT NOT NULL,
  status VARCHAR(32) NOT NULL,
  output TEXT NULL,
  error_message TEXT NULL,
  started_at TIMESTAMP(3) NOT NULL,
  finished_at TIMESTAMP(3) NOT NULL,
  duration_ms BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP(3) NULL,
  updated_at TIMESTAMP(3) NULL,
  deleted_at TIMESTAMP(3) NULL
);

CREATE INDEX IF NOT EXISTS idx_scheduled_task_logs_tenant_task ON scheduled_task_logs (tenant_id, task_id);
CREATE INDEX IF NOT EXISTS idx_scheduled_task_logs_deleted_at ON scheduled_task_logs (deleted_at);
