CREATE TABLE IF NOT EXISTS role_permissions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
  role VARCHAR(64) NOT NULL,
  permission VARCHAR(128) NOT NULL,
  created_at TIMESTAMP(3) NULL,
  updated_at TIMESTAMP(3) NULL,
  deleted_at TIMESTAMP(3) NULL,
  CONSTRAINT uk_role_tenant_permission UNIQUE (tenant_id, role, permission)
);

CREATE INDEX IF NOT EXISTS idx_role_permissions_tenant ON role_permissions (tenant_id);
CREATE INDEX IF NOT EXISTS idx_role_permissions_deleted_at ON role_permissions (deleted_at);
