CREATE TABLE IF NOT EXISTS scheduled_tasks (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
  name VARCHAR(128) NOT NULL,
  spec VARCHAR(64) NOT NULL,
  command VARCHAR(1024) NOT NULL,
  timeout_sec INT NOT NULL DEFAULT 0,
  concurrency_policy VARCHAR(16) NOT NULL DEFAULT 'forbid',
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  last_run_at TIMESTAMP(3) NULL,
  last_status VARCHAR(32) NULL,
  last_message VARCHAR(255) NULL,
  created_at TIMESTAMP(3) NULL,
  updated_at TIMESTAMP(3) NULL,
  deleted_at TIMESTAMP(3) NULL,
  CONSTRAINT uk_scheduled_tasks_tenant_name UNIQUE (tenant_id, name)
);

CREATE INDEX IF NOT EXISTS idx_scheduled_tasks_tenant ON scheduled_tasks (tenant_id);
CREATE INDEX IF NOT EXISTS idx_scheduled_tasks_enabled ON scheduled_tasks (enabled);
CREATE INDEX IF NOT EXISTS idx_scheduled_tasks_enabled_id ON scheduled_tasks (enabled, id);
CREATE INDEX IF NOT EXISTS idx_scheduled_tasks_deleted_at ON scheduled_tasks (deleted_at);
