CREATE TABLE IF NOT EXISTS scheduled_task_logs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
  task_id BIGINT NOT NULL,
  status VARCHAR(32) NOT NULL,
  output TEXT NULL,
  error_message TEXT NULL,
  started_at TIMESTAMP(3) NOT NULL,
  finished_at TIMESTAMP(3) NOT NULL,
  duration_ms BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP(3) NULL,
  updated_at TIMESTAMP(3) NULL,
  deleted_at TIMESTAMP(3) NULL
);

CREATE INDEX IF NOT EXISTS idx_scheduled_task_logs_tenant_task ON scheduled_task_logs (tenant_id, task_id);
CREATE INDEX IF NOT EXISTS idx_scheduled_task_logs_deleted_at ON scheduled_task_logs (deleted_at);
