CREATE TABLE IF NOT EXISTS menus (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
  name VARCHAR(128) NOT NULL,
  path VARCHAR(255) NOT NULL,
  perm_code VARCHAR(128) NOT NULL,
  sort INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP(3) NULL,
  updated_at TIMESTAMP(3) NULL,
  deleted_at TIMESTAMP(3) NULL,
  CONSTRAINT uk_menus_tenant_path UNIQUE (tenant_id, path)
);

CREATE INDEX IF NOT EXISTS idx_menus_tenant ON menus (tenant_id);
CREATE INDEX IF NOT EXISTS idx_menus_deleted_at ON menus (deleted_at);

CREATE TABLE IF NOT EXISTS role_menus (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
  role VARCHAR(64) NOT NULL,
  menu_id BIGINT NOT NULL,
  created_at TIMESTAMP(3) NULL,
  updated_at TIMESTAMP(3) NULL,
  deleted_at TIMESTAMP(3) NULL,
  CONSTRAINT uk_role_tenant_menu UNIQUE (tenant_id, role, menu_id)
);

CREATE INDEX IF NOT EXISTS idx_role_menus_tenant ON role_menus (tenant_id);
CREATE INDEX IF NOT EXISTS idx_role_menus_deleted_at ON role_menus (deleted_at);
