CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
  username VARCHAR(64) NOT NULL,
  password VARCHAR(255) NOT NULL,
  nickname VARCHAR(64) DEFAULT '',
  created_at TIMESTAMP(3) NULL,
  updated_at TIMESTAMP(3) NULL,
  deleted_at TIMESTAMP(3) NULL,
  CONSTRAINT uk_users_tenant_username UNIQUE (tenant_id, username)
);

CREATE INDEX IF NOT EXISTS idx_users_tenant ON users (tenant_id);
CREATE INDEX IF NOT EXISTS idx_users_deleted_at ON users (deleted_at);
