CREATE TABLE IF NOT EXISTS system_setting_histories (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  setting_id BIGINT NOT NULL,
  setting_key VARCHAR(128) NOT NULL,
  action VARCHAR(16) NOT NULL,
  before_value TEXT NOT NULL,
  before_type VARCHAR(16) NOT NULL DEFAULT '',
  before_group VARCHAR(64) NOT NULL DEFAULT '',
  before_remark VARCHAR(255) NOT NULL DEFAULT '',
  before_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  after_value TEXT NOT NULL,
  after_type VARCHAR(16) NOT NULL DEFAULT '',
  after_group VARCHAR(64) NOT NULL DEFAULT '',
  after_remark VARCHAR(255) NOT NULL DEFAULT '',
  after_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  operator_user_id BIGINT NOT NULL DEFAULT 0,
  operator_role VARCHAR(32) NOT NULL DEFAULT '',
  reason VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sys_setting_hist_setting_created ON system_setting_histories (setting_id, created_at);
CREATE INDEX IF NOT EXISTS idx_sys_setting_hist_key_created ON system_setting_histories (setting_key, created_at);
