package service

import (
	"context"

	"gin-scaffold/internal/model"
)

type AnnouncementServiceRepo interface {
	Create(ctx context.Context, in *model.Announcement) error
	Update(ctx context.Context, in *model.Announcement) error
	GetByID(ctx context.Context, id int64) (*model.Announcement, error)
	List(ctx context.Context, offset, limit int) ([]model.Announcement, int64, error)
	Delete(ctx context.Context, id int64) error
}

// AnnouncementService generated by cmd/gen crud.
type AnnouncementService struct {
	dao AnnouncementServiceRepo
}

func NewAnnouncementService(d AnnouncementServiceRepo) *AnnouncementService {
	return &AnnouncementService{dao: d}
}

func (s *AnnouncementService) Create(ctx context.Context, in *model.Announcement) error {
	return s.dao.Create(ctx, in)
}

func (s *AnnouncementService) Update(ctx context.Context, in *model.Announcement) error {
	return s.dao.Update(ctx, in)
}

func (s *AnnouncementService) GetByID(ctx context.Context, id int64) (*model.Announcement, error) {
	return s.dao.GetByID(ctx, id)
}

func (s *AnnouncementService) List(ctx context.Context, page, pageSize int) ([]model.Announcement, int64, error) {
	if page < 1 {
		page = 1
	}
	if pageSize <= 0 || pageSize > 100 {
		pageSize = 20
	}
	offset := (page - 1) * pageSize
	return s.dao.List(ctx, offset, pageSize)
}

func (s *AnnouncementService) Delete(ctx context.Context, id int64) error {
	return s.dao.Delete(ctx, id)
}
