package dao

import (
	"context"

	"gorm.io/gorm"

	"gin-scaffold/internal/model"
)

// AnnouncementDAO generated by cmd/gen crud.
type AnnouncementDAO struct {
	db *gorm.DB
}

func NewAnnouncementDAO(db *gorm.DB) *AnnouncementDAO {
	return &AnnouncementDAO{db: db}
}

func (d *AnnouncementDAO) Create(ctx context.Context, in *model.Announcement) error {
	return d.db.WithContext(ctx).Create(in).Error
}

func (d *AnnouncementDAO) Update(ctx context.Context, in *model.Announcement) error {
	return d.db.WithContext(ctx).Save(in).Error
}

func (d *AnnouncementDAO) GetByID(ctx context.Context, id int64) (*model.Announcement, error) {
	var row model.Announcement
	if err := d.db.WithContext(ctx).First(&row, id).Error; err != nil {
		return nil, err
	}
	return &row, nil
}

func (d *AnnouncementDAO) List(ctx context.Context, offset, limit int) ([]model.Announcement, int64, error) {
	var total int64
	if err := d.db.WithContext(ctx).Model(&model.Announcement{}).Count(&total).Error; err != nil {
		return nil, 0, err
	}
	var rows []model.Announcement
	if err := d.db.WithContext(ctx).Order("id desc").Offset(offset).Limit(limit).Find(&rows).Error; err != nil {
		return nil, 0, err
	}
	return rows, total, nil
}

func (d *AnnouncementDAO) Delete(ctx context.Context, id int64) error {
	return d.db.WithContext(ctx).Delete(&model.Announcement{}, id).Error
}
