INSERT INTO role_permissions (tenant_id, role, permission, created_at, updated_at) VALUES
  ('default', 'admin', 'db:ping', NOW(), NOW()),
  ('default', 'admin', 'user:read', NOW(), NOW()),
  ('default', 'admin', 'user:create', NOW(), NOW()),
  ('default', 'admin', 'user:update', NOW(), NOW()),
  ('default', 'admin', 'user:delete', NOW(), NOW()),
  ('default', 'admin', 'user:export', NOW(), NOW()),
  ('default', 'admin', 'task:read', NOW(), NOW()),
  ('default', 'admin', 'task:create', NOW(), NOW()),
  ('default', 'admin', 'task:update', NOW(), NOW()),
  ('default', 'admin', 'task:delete', NOW(), NOW()),
  ('default', 'admin', 'task:toggle', NOW(), NOW()),
  ('default', 'admin', 'task:run', NOW(), NOW()),
  ('default', 'admin', 'menu:read', NOW(), NOW()),
  ('default', 'user', 'user:read', NOW(), NOW()),
  ('default', 'admin', 'audit:read', NOW(), NOW()),
  ('default', 'admin', 'audit:export', NOW(), NOW()),
  ('default', 'admin', 'sys:config:read', NOW(), NOW()),
  ('default', 'admin', 'sys:config:write', NOW(), NOW()),
  ('default', 'admin', 'sys:config:rollback', NOW(), NOW()),
  ('default', 'admin', 'sys:config:publish', NOW(), NOW()),
  ('default', 'admin', 'announcement:read', NOW(), NOW()),
  ('default', 'admin', 'announcement:write', NOW(), NOW()),
  ('default', 'admin', 'menu:catalog', NOW(), NOW()),
  ('default', 'admin', 'menu:create', NOW(), NOW()),
  ('default', 'admin', 'menu:update', NOW(), NOW()),
  ('default', 'admin', 'menu:delete', NOW(), NOW())
ON CONFLICT (tenant_id, role, permission) DO NOTHING;
